const mongoose = require('mongoose');
const govschema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    hotels:[{
        hotelname:{
            type:String,
            required:true
        },
        isFavorite: {
            type: Boolean,
            default: false
        },
        number:{
            type:String,
            required:true
        },
        
        rate:{
            type:String,
            required:false
        },
        link:{
            type:String,
            required:false
        },
        img:{
            type:String,
            required:true
        },
       
        time:[{
            Saterday:{
                type:String,
            },
            Sunday:{
                type:String,
            },
            Monday:{
                type:String,
            },
            Tuesday:{
                type:String,
            },
            wednesday:{
                type:String,
            },
            thursday:{
                type:String,
            },
            Friday:{
                type:String,
            }
        }],
      
        description:{
            type:String,
            required:false
        },
        location:{
            type:String,
            required:false
        }
    }],
    Restaurants:[{
    Restaurantsname:{
            type:String,
            required:true
        },
        isFavorite: {
            type: Boolean,
            default: false
        },
        number:{
            type:String,
            required:true
        },
        rate:{
            type:String,
            required:false
        },
        link:{
            type:String,
            required:false
        },
        img:{
            type:String,
            required:true
        },
        time:[{
            Saterday:{
                type:String,
            },
            Sunday:{
                type:String,
            },
            Monday:{
                type:String,
            },
            Tuesday:{
                type:String,
            },
            wednesday:{
                type:String,
            },
            thursday:{
                type:String,
            },
            Friday:{
                type:String,
            }
        }],
        
        description:{
            type:String,
            required:false
        },
        location:{
            type:String,
            required:false
        }
    }],
    museums:[{
        museumsname:{
                type:String,
                required:true
            },
            isFavorite: {
                type: Boolean,
                default: false
            },
            number:{
                type:String,
                required:true
            },
            rate:{
                type:String,
                required:false
            },
            link:{
                type:String,
                required:false
            },
            img:{
                type:String,
                required:true
            },
            time:[{
                Saterday:{
                    type:String,
                },
                Sunday:{
                    type:String,
                },
                Monday:{
                    type:String,
                },
                Tuesday:{
                    type:String,
                },
                wednesday:{
                    type:String,
                },
                thursday:{
                    type:String,
                },
                Friday:{
                    type:String,
                }
            }],
            description:{
                type:String,
                required:false
            },
            location:{
                type:String,
                required:false
            }
        }],
        historicalsites:[{
            historicalname:{
                type:String,
                required:true
            },
            isFavorite: {
                type: Boolean,
                default: false
            },
            number:{
                type:String,
                required:true
            },
            rate:{
                type:String,
                required:false
            },
            link:{
                type:String,
                required:false
            },
            img:{
                type:String,
                required:true
            },
            time:[{
                Saterday:{
                    type:String,
                },
                Sunday:{
                    type:String,
                },
                Monday:{
                    type:String,
                },
                Tuesday:{
                    type:String,
                },
                wednesday:{
                    type:String,
                },
                thursday:{
                    type:String,
                },
                Friday:{
                    type:String,
                }
            }],
            
            description:{
                type:String,
                required:false
            },
            location:{
                type:String,
                required:false
            }
        }],
        img:{
            type:String,
            required:true
        }
})

module.exports=mongoose.model("governorates",govschema);